name: Update README with sorted company links

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches:
      - main
    paths:
      - "*/**"       # Trigger on changes inside any top-level folder
      - "!README.md" # Ignore changes to README itself

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get all top-level folders
        id: get-folders
        run: |
          # Get all top-level directories (ignore .github, .git, .)
          all_dirs=$(find . -maxdepth 1 -type d ! -name ".github" ! -name "." ! -name ".git" | sed 's|./||' | sort)
          echo "all_dirs=$all_dirs" >> $GITHUB_OUTPUT

      - name: Update README with sorted companies
        run: |
          # Extract content before the first company list
          awk '/^- \[/{exit} {print}' README.md > README.tmp

          # Add sorted company list
          echo >> README.tmp
          echo "### COMPANIES" >> README.tmp
          echo >> README.tmp

          # Read all_dirs into array
          IFS=' ' read -r -a folders <<< "${{ steps.get-folders.outputs.all_dirs }}"

          # Loop over array safely
          for dir in "${folders[@]}"; do
            echo "- [${dir}](./${dir})" >> README.tmp
          done

          # Replace README.md
          mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update README with sorted company links"
          git push
