name: Update README with new folder links

on:
  push:
    branches:
      - main
    paths:
      - "*/**"   # Trigger on changes inside any top-level folder
  workflow_dispatch:   # Manual trigger

permissions:
  contents: write   # Allow pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get all top-level folders
        id: get-folders
        run: |
          # Get all top-level directories (ignore .github, .git)
          all_dirs=$(find . -maxdepth 1 -type d ! -name ".github" ! -name "." ! -name ".git" | sed 's|./||' | sort)
          echo "all_dirs=$all_dirs" >> $GITHUB_OUTPUT

      - name: Update README with sorted companies
        run: |
          # Extract content before the companies list
          awk '/^- \[/{exit} {print}' README.md > README.tmp

          # Add sorted company list
          echo >> README.tmp
          echo "### COMPANIES" >> README.tmp
          echo >> README.tmp
          for dir in ${{ steps.get-folders.outputs.all_dirs }}; do
            echo "- [${dir}](./${dir})" >> README.tmp
          done

          # Replace README.md
          mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update README with sorted company links"
          git push
