name: Update README with new folder links

on:
  push:
    branches:
      - main
    paths:
      - "*/**"   # trigger if a top-level folder or files inside it change
  workflow_dispatch:   # manual trigger

permissions:
  contents: write   # 👈 allow pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          # Extract part before "### COMPANIES"
          before=$(awk '/### COMPANIES/{exit} {print}' README.md)

          # Extract part after the *first blank line* following COMPANIES
          after=$(awk '/### COMPANIES/{flag=1;next} flag && NF==0{flag=0;next} !flag{print}' README.md)

          # Get all top-level directories (ignore .github)
          dirs=$(ls -d */ | grep -v ".github" | sed 's#/##' | sort -u)

          # Rebuild company list alphabetically
          company_list=""
          for d in $dirs; do
            company_list="${company_list}- [${d}](./${d})\n"
          done

          # Rewrite README cleanly
          {
            echo "$before"
            echo "### COMPANIES"
            echo
            printf "%b" "$company_list"
            echo
            echo "$after"
          } > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README with new folder link" || echo "No changes to commit"
          git push
