name: Update README with new folder links

on:
  push:
    branches:
      - main
    paths:
      - "*/**"   # Trigger on changes inside any top-level folder
  workflow_dispatch:   # Manual trigger

permissions:
  contents: write   # Allow pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          # Split README into 2 parts: before COMPANIES and after COMPANIES
          before=$(awk '/### COMPANIES/{exit} {print}' README.md)
          after=$(awk '/### COMPANIES/{found=1;next} found{print}' README.md)

          # Get all top-level directories (ignore .github)
          dirs=$(find . -maxdepth 1 -type d ! -name ".github" ! -name "." | sed 's|./||' | sort -u)

          # Rebuild company list alphabetically
          company_list=""
          while IFS= read -r d; do
            company_list="${company_list}- [${d}](./${d})"$'\n'
          done <<< "$dirs"

          # Rewrite README without duplicates
          {
            echo "$before"
            echo "### COMPANIES"
            echo
            printf "%b" "$company_list"
            echo "$after"
          } > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README with new folder links" || echo "No changes to commit"
          git push
