name: Update README with new folder links

on:
  push:
    branches:
      - main
    paths:
      - "*/"   # trigger if a top-level folder is added or changed
  workflow_dispatch:   # manual trigger

permissions:
  contents: write   # allow pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          # Split README into 2 parts: before COMPANIES and after COMPANIES
          before=$(awk '/### COMPANIES/{exit} {print}' README.md)
          after=$(awk '/### COMPANIES/{found=1;next} found{print}' README.md)

          # Get all top-level directories (ignore .github)
          dirs=$(ls -d */ | grep -v ".github" | sed 's#/##' | sort)

          # Only add directories not already in README
          company_list=""
          for d in $dirs; do
            if ! grep -q "\[${d}\]" README.md; then
              company_list="${company_list}- [${d}](./${d})\n"
            fi
          done

          # Rewrite README only if there are new folders
          if [ -n "$company_list" ]; then
            {
              echo "$before"
              echo "### COMPANIES"
              echo
              printf "%b" "$company_list"
              echo "$after"
            } > README.md
          fi

      - name: Commit and push changes
        if: success() && steps.update-readme.outputs.changed == 'true' || always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README with new folder link" || echo "No changes to commit"
          git push
